=== Fauzifaruqn/SemantikWeb/Pertemuan 2/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.example.org/Schema"
xmlns:tns="http://www.example.org/Schema"
elementFormDefault="qualified">


<complexType name="tipekomoditi">
    <sequence>
        <element name="barang" type="tns:tipebarang" minOccurs="1"
        maxOccurs="3"></element>
    </sequence>
</complexType>

<complexType name="tipebarang">
    <sequence>
        <element name="nama" type="string"></element>
        <element name="harga" type="tns:harganya"></element>
    </sequence>
    <attribute name="bid" type="ID" use="required"></attribute>
</complexType>

<element name="globalkategori" type="tns:tipekomoditi"></element>

<simpleType name="harganya">
    <restriction base="integer">
        <minInclusive value="1000"></minInclusive>
        <maxInclusive value="10000"></maxInclusive>
    </restriction>
</simpleType>

</schema>

=== Fauzifaruqn/SemantikWeb/Pertemuan 2/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalkategori
xmlns:tns = "http://www.example.org/Schema"
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/Schema schema.xsd"
>
    <tns:barang bid = "B1">
        <tns:nama> Barang 1 </tns:nama>
        <tns:harga> 3000 </tns:harga>
    </tns:barang>

    <tns:barang bid = "B2">
        <tns:nama> Barang 2 </tns:nama>
        <tns:harga> 3000 </tns:harga>
    </tns:barang>

    
    <tns:barang bid = "B3">
        <tns:nama> Barang 3 </tns:nama>
        <tns:harga> 3000 </tns:harga>
    </tns:barang>

    
    <tns:barang bid = "B4">
        <tns:nama> Barang 4 </tns:nama>
        <tns:harga> 3000 </tns:harga>
    </tns:barang>
    
</tns:globalkategori>
